### ISSUE TITLE
What Java Version does this plugin use ?

### ISSUE THREAD

**Issue by Nash-x9** [nccgroup/freddy#20]
When I install this plugin,it has a errors.
`java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.dg3.a(Unknown Source)
	at burp.dg3.<init>(Unknown Source)
	at burp.b8r.a(Unknown Source)
	at burp.ba8.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.
`

**Comment by vdbaan** [comment]
Freddy is compiled with Java 11 (as described by the message "class file version 55.0"). You tried to run it with Java 8 (version 52), which does not work.

**Comment by Nash-x9** [comment]
> Freddy is compiled with Java 11 (as described by the message "class file version 55.0"). You tried to run it with Java 8 (version 52), which does not work.

Thanks! It works.
