### ISSUE TITLE
Extension generated task deleted

### ISSUE THREAD

**Issue by fenceposterror** [nccgroup/freddy#7]
During a pentest of a soap interface I started getting this error message in the logs:

```	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:896)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
java.lang.RuntimeException: Extension generated task deleted
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at burp.djm.makeHttpRequest(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
java.lang.RuntimeException: Extension generated task deleted
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at burp.cz0.run(Unknown Source)
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
java.lang.RuntimeException: Extension generated task deleted
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at burp.djm.makeHttpRequest(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:896)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:896)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Extension generated task deleted
	at burp.djm.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.cz0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Not sure how I can reproduce it, sorry to not have more right now. Using the latest and greatest Burp (2.0.16).

**Comment by vdbaan** [comment]
Hi fenceposterror,

Thanks for reporting this. I will try to see what the reason behind this error is and resolve it.

Steven.

**Comment by vdbaan** [comment]
Hi,

according to portswigger: "It looks like a user cancelled the scan while the Freddy scan check was active. It’s probably not necessary to do anything about this – the check exiting with an exception when the scan is cancelled seems like reasonable semantics."

This means that the exception is generated outside of the scope of the extension and as I cannot do anything with the exception I should not catch it (catching and ignoring an exception is bad practice). 

I hope that I have given good enough explanation to close the issue.

Thanks,
Steven.
