### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Hipapheralkus** [nccgroup/freddy#8]
I’m facing some memory problems during large Active scans, when I have Freddy enabled. It fails after a couple of hours, on a single thread.
I'm running Burp from CMD:
`"C:\Program Files\BurpSuitePro\jre\bin\java.exe" -jar "C:\Program Files\BurpSuitePro\burpsuite_pro.jar" -Xmx6g -Djava.net.preferIPv4Stack=true`

I'm running Burp on a single thread, with Private collaborator server configured. Every time I switch off this extension, everything works fine and memory imprint is not so large. At this moment, even with limiting java to 6GB, the Burp process takes 20+ GB. I would like to give you more information, so what else could I supply to you?
OS: Windows Server 2016, build 1607
RAM: 78GB
CPU: Intel Xeon E5-2683 v3 @ 2GHz

**Comment by vdbaan** [comment]
Hi Hipapheralkus,

thank you for reporting this. I started to look into this issue. Can you inform me what type of application you where scanning (Java/.NET) to replicate the test.

Thanks,
Steven.

**Comment by Hipapheralkus** [comment]
Certainly, it was Java

**Comment by Hipapheralkus** [comment]
I performed scan only with Freddy extension enabled; and only active scan with Extensions = no other active/passive tests. The Burp UI is very unresponsive, it takes more than 10 seconds to switch to other tab (e.g. Alerts). Here is the Errors log of extension:
```
 	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:882)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:896)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:896)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at burp.tq.a(Unknown Source)
	at burp.aph.makeHttpRequest(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:832)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:388)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by fenceposterror** [comment]
Hi, I observe the same behavior. Also a Java application that I'm testing. One can watch how the memory is being eaten (~7GB in 10 minutes). Without the extension, the used memory climbs about 20 mb in 10 minutes.
OS: RHEL7
Burp 2.0.17.

**Comment by vdbaan** [comment]
Hi,

I am doing my best to resolve this issue as soon as possible. I currently ask for your patience.

Thanks,
Steven.

**Comment by vdbaan** [comment]
Found the underlying issue. The collaborator records were never removed. This will be fixed in the next release.
